tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"

brew "anyenv"
brew "bat"
brew "ghq"
brew "git"
brew "nvim"
brew "neovim"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "peco"
brew "tig"
brew "fd"
brew "fzf"
brew "tmux"
brew "lazygit"

cask "1password"
cask "appcleaner"
cask "discord"
cask "docker"
cask "google-chrome"
cask "hyper"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "slack"
cask "visual-studio-code"
