#!/bin/zsh

NEOVIM_CONFIG_PATH="$HOME/.config/nvim"
DEIN_VIM_INSTALL_PATH="$HOME/.cache/dein"
HOMEBREW_DEPENDENCIES=(nvim anyenv)
NODE_VERSION='16.13.2'

echo 'Start install neovim!!!'

echo ''
echo '#####################################'
echo '##       Setup neovim config        ##'
echo '######################################'
echo "Make diresctory ${NEOVIM_CONFIG_PATH}"
rm -fr $NEOVIM_CONFIG_PATH
mkdir -p $NEOVIM_CONFIG_PATH
echo 'Copy neovim config'
cp -Rf init.vim init dein $NEOVIM_CONFIG_PATH

echo ''
echo '######################################'
echo '##           Install dein           ##'
echo '######################################'
if [[ ! -e $DEIN_VIM_INSTALL_PATH/repos ]] then
  installer_sh_path=./installer.sh
  echo 'Download dein.vim'
  curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > $installer_sh_path
  echo 'Install dein.vim'
  sh $installer_sh_path $DEIN_VIM_INSTALL_PATH
  rm $installer_sh_path
  echo 'Done'
else
  echo 'Installed dein.vim'
fi

echo ''
echo '######################################'
echo '##       Install dependencies       ##'
echo '######################################'
for dependencie in "${HOMEBREW_DEPENDENCIES[@]}"
do
  if ! builtin command -v $dependencie > /dev/null; then
    echo "Install $dependencie"
    brew install $dependencie
    brew cleanup $dependencie
    if $dependencie == 'anyenv'; then
      # コケたら以下を実行してみる
      # zsh にパスを通す
      # $ echo 'eval "$(anyenv init -)"' >> ~/.zshrc
      # # anyenv の初期化
      # $ annyenv init
      # シェルを再起動
      # $ exec $SHELL -l
      echo "Initialize $dependncie"
      yes | anyenv install --init
      source ~/.zshrc
    fi
  else
    echo "Installed $dependencie"
  fi
done

echo ''
echo '######################################'
echo '##          Install nodenv          ##'
echo '######################################'
if ! builtin command -v nodenv > /dev/null; then
  echo 'Install nodenv'
  yes | anyenv install nodenv
else
  echo 'Installed nodenv'
fi

echo ''
echo '######################################'
echo '##           Install node           ##'
echo '######################################'
if ! builtin command -v node > /dev/null; then
  echo "Install node version is $NODE_VERSION"
  yes | nodenv install $NODE_VERSION
  nodenv rehash
  nodenv global $NODE_VERSION
else
  echo "Installed node (version: $(node -v))"
fi

echo ''
echo '######################################'
echo '##           Install yarn           ##'
echo '######################################'
if ! builtin command -v yarn > /dev/null; then
  echo "Install yarn"
  npm install -g yarn
  echo 'export PATH=$PATH:`npm bin -g`' >> ~/.zshrc
  source ~/.zshrc >> /dev/null
else
  echo 'Installed yarn'
fi


echo 'Neovim install completed!!!'
