###### dein 本体 ######
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

###### カレンダー ######
[[plugins]]
repo = 'itchyny/calendar.vim'

###### タブのアイコンを表示したりするやつ ######
[[plugins]]
repo = 'romgrk/barbar.nvim'
